"""Public constants that form part of the compatibility contract."""

from __future__ import annotations

SCHEMA_VERSION = 3
PACKAGE_SCHEMA = "continuityforge.memory-pack/v0.2"
V01_PACKAGE_SCHEMA = "continuityforge.memory-pack/v0.1"

EXIT_OK = 0
EXIT_USAGE = 2
EXIT_VALIDATION_FAILED = 3
EXIT_GOVERNANCE_FAILED = 4
EXIT_LEDGER_FAILED = 5
EXIT_SCHEMA_FAILED = 6

# Frozen command-line lifecycle and serialization contract for v0.3.  Commands
# outside these sets must opt in explicitly rather than inheriting a writable
# ``Storage`` constructor by accident.
CLI_ERROR_SCHEMA = "continuityforge.error/v0.3"
CLI_LIFECYCLE_CREATE_CAPABLE = "create-capable"
CLI_LIFECYCLE_WRITE_EXISTING = "write-existing"
CLI_LIFECYCLE_READ_EXISTING = "read-existing"
CLI_LIFECYCLE_EXPLICIT_MIGRATE = "explicit-migrate"

CLI_COMMAND_LIFECYCLE = {
    "ingest": CLI_LIFECYCLE_CREATE_CAPABLE,
    "demo": CLI_LIFECYCLE_CREATE_CAPABLE,
    "claim-propose": CLI_LIFECYCLE_WRITE_EXISTING,
    "claim-add": CLI_LIFECYCLE_WRITE_EXISTING,
    "claim-review": CLI_LIFECYCLE_WRITE_EXISTING,
    "event-add": CLI_LIFECYCLE_WRITE_EXISTING,
    "source-list": CLI_LIFECYCLE_READ_EXISTING,
    "claim-list": CLI_LIFECYCLE_READ_EXISTING,
    "validate": CLI_LIFECYCLE_READ_EXISTING,
    "compile": CLI_LIFECYCLE_READ_EXISTING,
    "ledger-verify": CLI_LIFECYCLE_READ_EXISTING,
    "ledger-show": CLI_LIFECYCLE_READ_EXISTING,
    "source-impact": CLI_LIFECYCLE_READ_EXISTING,
    "migration-check": CLI_LIFECYCLE_READ_EXISTING,
    "migrate": CLI_LIFECYCLE_EXPLICIT_MIGRATE,
}

# ``SourceInputError`` and inspection errors intentionally expose only these
# machine-readable codes.  An arbitrary exception ``.code`` is never copied
# into the public envelope.
CLI_STABLE_DOMAIN_ERROR_CODES = frozenset(
    {
        "AFFECTED_EVIDENCE_BYTES_LIMIT_EXCEEDED",
        "AFFECTED_EVIDENCE_LIMIT_EXCEEDED",
        "ANSI_CONTROL",
        "BIDI_CONTROL",
        "CLAIM_METADATA_BYTES_LIMIT",
        "CLAIM_RATIONALE_BYTES_LIMIT",
        "CLAIM_TEXT_BYTES_LIMIT",
        "CLAIM_AUTHORITY_INVALID",
        "CLAIM_AUTHORITY_MATERIAL_INCONSISTENT",
        "CLAIM_AUTHORITY_SCOPE_MISMATCH",
        "DUPLICATE_JSON_KEY",
        "EVENT_AUDIT_INVALID",
        "EVENT_DETAILS_INVALID",
        "EVENT_SUMMARY_BYTES_LIMIT",
        "EVENT_TITLE_BYTES_LIMIT",
        "EVIDENCE_QUOTE_BYTES_LIMIT",
        "EVIDENCE_QUOTE_LINES_LIMIT",
        "IMPACT_PATTERN_LINES_LIMIT_EXCEEDED",
        "IMPACT_REPORT_CANDIDATE_LIMIT_EXCEEDED",
        "INSPECTION_AUTHORITY_BYTES_LIMIT_EXCEEDED",
        "INSPECTION_AUTHORITY_RECORD_LIMIT_EXCEEDED",
        "INSPECTION_EVENT_AUDIT_BYTES_LIMIT_EXCEEDED",
        "INSPECTION_EVENT_AUDIT_RECORD_LIMIT_EXCEEDED",
        "INSPECTION_LEDGER_ENTRY_LIMIT_EXCEEDED",
        "INSPECTION_LEDGER_PAYLOAD_LIMIT_EXCEEDED",
        "INVALID_JSON",
        "INVALID_UNICODE",
        "JSON_NESTING_LIMIT",
        "JSON_RESOURCE_EXHAUSTED",
        "LEDGER_PAYLOAD_INVALID",
        "MAX_FILE_BYTES",
        "MAX_LINE_BYTES",
        "MAX_LINES",
        "NONFINITE_JSON_NUMBER",
        "NUL_BYTE",
        "REPORT_METADATA_BYTES_LIMIT_EXCEEDED",
        "REPORT_METADATA_CONTROL_CHARACTER",
        "REPORT_METADATA_INVALID",
        "REPORT_METADATA_INVALID_UNICODE",
        "SNAPSHOT_BYTES_LIMIT_EXCEEDED",
        "SNAPSHOT_CONTENT_HASH_INVALID",
        "SNAPSHOT_CONTENT_HASH_MISMATCH",
        "SNAPSHOT_CONTENT_INVALID_UNICODE",
        "SNAPSHOT_CONTENT_MISSING",
        "SNAPSHOT_LINE_BYTES_LIMIT_EXCEEDED",
        "SNAPSHOT_LINE_COUNT_MISMATCH",
        "SNAPSHOT_LINES_LIMIT_EXCEEDED",
        "SNAPSHOT_METADATA_INCONSISTENT",
        "SOURCE_DECODE_ERROR",
        "SOURCE_REVISION_LIMIT_EXCEEDED",
        "TARGET_SNAPSHOT_BYTES_LIMIT",
        "TARGET_SNAPSHOT_CONTENT_INVALID_UNICODE",
        "TARGET_SNAPSHOT_CONTENT_MISSING",
        "TARGET_SNAPSHOT_ID_REQUIRED",
        "TARGET_SNAPSHOT_LINE_BYTES_LIMIT",
        "TARGET_SNAPSHOT_LINES_LIMIT",
        "TARGET_SNAPSHOT_REQUIRED",
        "TARGET_SNAPSHOT_VERSION_INVALID",
        "TOO_MANY_EXACT_MATCHES",
    }
)

SUPPORTED_SOURCE_SUFFIXES = frozenset(
    {".txt", ".md", ".markdown", ".json", ".srt"}
)
